name: Build OEC‑Turbo Armbian
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 120
    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@master

      - name: Checkout code
        uses: actions/checkout@v4
        submodules: true

      - name: Install docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl enable --now docker

      - name: Compile OEC‑Turbo image
        run: |
          ./compile.sh docker \
          BOARD=rockchip-efused-wxy-oec \
          BRANCH=legacy \
          RELEASE=bookworm \
          BUILD_MINIMAL=no \
          BUILD_DESKTOP=no \
          KERNEL_CONFIGURE=no \
          COMPRESS_OUTPUTIMAGE=img.gz

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: oec-turbo-armbian-img
          path: output/images/*.img.gz
